# Document the purpose of the order domain model module.
# Provide the module docstring for order domain models.
# Start the module docstring for order domain models.
"""Order domain models."""
# Summarize what the order models provide.
# Overview: Defines order status values and the order record schema.
# Explain why dataclasses are used in this module.
# Details: Dataclasses are used for clean serialization between layers.

# Enable postponed evaluation for type hints to keep annotations simple.
from __future__ import annotations

# Import dataclass helpers for concise record definitions.
from dataclasses import dataclass, field
# Import datetime utilities to timestamp orders and normalize to UTC.
from datetime import datetime, timezone
# Import typing helpers for JSON-like structures.
from typing import Any, Dict, Optional


# Define the only allowed order statuses so automation can validate updates.
ALLOWED_STATUSES = ("requested", "in_progress", "delivered", "cancelled")


# Enable dataclass generation for order records.
@dataclass(frozen=True)
# Represent an order record as an immutable snapshot for storage and reporting.
class OrderRecord:
    # Describe the order record dataclass for maintainers.
    """Immutable order record stored in SQLite."""

    # Store the numeric order identifier generated by persistence.
    order_id: int
    # Store the timestamp when the order was created.
    timestamp: datetime
    # Store the user identifier that placed the order.
    user_id: str
    # Store the current status used by orchestration logic.
    status: str
    # Store optional structured metadata about the order.
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Serialize an order record to a JSON-ready dict.
    def to_dict(self) -> Dict[str, Any]:
        # Describe the serialization behavior.
        """Serialize the record for JSON responses."""
        # Convert the timestamp to UTC for consistent API responses.
        timestamp = self.timestamp.astimezone(timezone.utc)
        # Build a JSON-ready dictionary for API clients and dashboards.
        return {
            # Provide the order ID under the API field name.
            "id": self.order_id,
            # Provide an ISO-8601 timestamp in UTC with Z suffix.
            "timestamp": timestamp.isoformat().replace("+00:00", "Z"),
            # Provide the user ID so UI can display who placed it.
            "user_id": self.user_id,
            # Provide the status so automation and UI can render progress.
            "status": self.status,
            # Provide metadata for any extra order context.
            "metadata": self.metadata,
            # Close out the dictionary literal.
        }


# Enable dataclass generation for order creation requests.
@dataclass
# Describe the payload expected when creating a new order.
class OrderCreateRequest:
    # Describe the order creation dataclass for maintainers.
    """Payload for new order creation."""

    # Capture the user ID that will be associated with the new order.
    user_id: str
    # Capture optional metadata such as RFID or train selection.
    metadata: Dict[str, Any] = field(default_factory=dict)


# Enable dataclass generation for order update requests.
@dataclass
# Describe the payload expected when updating an order status.
class OrderUpdateRequest:
    # Describe the order update dataclass for maintainers.
    """Payload for updating an order status."""

    # Capture the order ID to update in persistent storage.
    order_id: int
    # Capture the new status that the orchestrator is applying.
    status: str
    # Capture optional metadata overrides for the order.
    metadata: Optional[Dict[str, Any]] = None
